name: Mister Vue
favicon: null
layout_spectrum: 0.94295
typography_spectrum: 0.08093191799707711
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fafafa'
    - '#020f15'
    - '#9b8fa5'
    - '#6c6575'
    - '#5d0523'
  brandStrength: 0.25
  lightness: 0.8125
  saturation: 0.875
  rhythmicContrast: 0.6465678131207824
purpose: []
