name: Mister Vue
favicon: null
layout_spectrum: 0.6556305773556232
typography_spectrum: 0.08093191799707711
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.12034957762807608
  lightness: 0.8618992583360523
  saturation: 0.9584838196169585
  rhythmicContrast: 0.6465678131207824
purpose: []
